In [ ]:
import pandas as pd

In [6]:
exoplanet_data = pd.read_csv('cumulative.csv', sep = ',')
exoplanet_data

,rowid,kepid,kepoi_name,kepler_name,koi_disposition,koi_pdisposition,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,...,koi_steff_err2,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag
0,1,10797460,K00752.01,Kepler-227 b,CONFIRMED,CANDIDATE,1.000,0,0,0,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
1,2,10797460,K00752.02,Kepler-227 c,CONFIRMED,CANDIDATE,0.969,0,0,0,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
2,3,10811496,K00753.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0,1,0,...,-176.0,4.544,0.044,-0.176,0.868,0.233,-0.078,297.00482,48.134129,15.436
3,4,10848459,K00754.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0,1,0,...,-174.0,4.564,0.053,-0.168,0.791,0.201,-0.067,285.53461,48.285210,15.597
4,5,10854555,K00755.01,Kepler-664 b,CONFIRMED,CANDIDATE,1.000,0,0,0,...,-211.0,4.438,0.070,-0.210,1.046,0.334,-0.133,288.75488,48.226200,15.509
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9559,9560,10031643,K07984.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0,0,0,...,-152.0,4.296,0.231,-0.189,1.088,0.313,-0.228,298.74921,46.973351,14.478
9560,9561,10090151,K07985.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0,1,1,...,-166.0,4.529,0.035,-0.196,0.903,0.237,-0.079,297.18875,47.093819,14.082
9561,9562,10128825,K07986.01,NaN,CANDIDATE,CANDIDATE,0.497,0,0,0,...,-220.0,4.444,0.056,-0.224,1.031,0.341,-0.114,286.50937,47.163219,14.757
9562,9563,10147276,K07987.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.021,0,0,1,...,-236.0,4.447,0.056,-0.224,1.041,0.341,-0.114,294.16489,47.176281,15.385
9563,9564,10156110,K07989.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0,0,1,...,-225.0,4.385,0.054,-0.216,1.193,0.410,-0.137,297.00977,47.121021,14.826

In [7]:
clean_col_used = [
    "koi_period",
    "koi_duration",
    "koi_depth",
    "koi_prad",
    "koi_teq",
    "koi_insol",
    "koi_model_snr",
    "koi_steff",
    "koi_slogg",
    "koi_srad",
    "koi_kepmag",
    "koi_disposition"
]

In [8]:
exoplanet_data = exoplanet_data[clean_col_used]
exoplanet_data

,koi_period,koi_duration,koi_depth,koi_prad,koi_teq,koi_insol,koi_model_snr,koi_steff,koi_slogg,koi_srad,koi_kepmag,koi_disposition
0,9.488036,2.95750,615.8,2.26,793.0,93.59,35.8,5455.0,4.467,0.927,15.347,CONFIRMED
1,54.418383,4.50700,874.8,2.83,443.0,9.11,25.8,5455.0,4.467,0.927,15.347,CONFIRMED
2,19.899140,1.78220,10829.0,14.60,638.0,39.30,76.3,5853.0,4.544,0.868,15.436,FALSE POSITIVE
3,1.736952,2.40641,8079.2,33.46,1395.0,891.96,505.6,5805.0,4.564,0.791,15.597,FALSE POSITIVE
4,2.525592,1.65450,603.3,2.75,1406.0,926.16,40.9,6031.0,4.438,1.046,15.509,CONFIRMED
...,...,...,...,...,...,...,...,...,...,...,...,...
9559,8.589871,4.80600,87.7,1.11,929.0,176.40,8.4,5638.0,4.296,1.088,14.478,FALSE POSITIVE
9560,0.527699,3.22210,1579.2,29.35,2088.0,4500.53,453.3,5638.0,4.529,0.903,14.082,FALSE POSITIVE
9561,1.739849,3.11400,48.5,0.72,1608.0,1585.81,10.6,6119.0,4.444,1.031,14.757,CANDIDATE
9562,0.681402,0.86500,103.6,1.07,2218.0,5713.41,12.3,6173.0,4.447,1.041,15.385,FALSE POSITIVE
9563,4.856035,3.07800,76.7,1.05,1266.0,607.42,8.2,6469.0,4.385,1.193,14.826,FALSE POSITIVE

In [ ]:
exoplanet_data = exoplanet_data.dropna()
exoplanet_data

In [ ]:
exoplanet_data = exoplanet_data[exoplanet_data["koi_disposition"].isin(["CONFIRMED", "FALSE POSITIVE"])]

In [ ]:
exoplanet_data["koi_disposition"] = exoplanet_data["koi_disposition"].map({"CONFIRMED": 1,"FALSE POSITIVE": 0})
exoplanet_data

In [ ]:
exoplanet_data.info()

In [9]:
exoplanet_data.to_csv('cleaned_exoplanet_data.csv', index=False, header=True)